name: Zato Docker Quickstart

on:
  push:
    branches:
      - dev

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zato-run-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Zato Docker Quickstart
        run: docker run ghcr.io/talexie/zato-3.2-quickstart:1.2